name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install llvm

      - name: Build project
        run: make all

      - name: Verify binaries exist
        run: |
          test -f build/countdown/process1
          test -f build/countdown/process2
          test -f build/buffer_transfer/consumer
          test -f build/buffer_transfer/producer
          test -f build/ring_buffer/consumer
          test -f build/ring_buffer/producer
          test -f build/mmap_file/db_creator
          test -f build/mmap_file/db_reader
          test -f build/mmap_file/db_writer
          test -f build/simd_processing/consumer
          test -f build/simd_processing/producer
